#!/usr/bin/env bash

RESOLUTION=0.0025
LEFT=125.0
BOTTOM=33.0
RIGHT=132.0
TOP=38.7
DATA=/data
OUTPUT=output.tiff


cd "${DATA}" || exit

WIDTH=$(python -c "print(int(abs(($RIGHT - $LEFT) / $RESOLUTION)))")
HEIHGT=$(python -c "print(int(abs(($BOTTOM - $TOP) / $RESOLUTION)))")

gdal_grid \
    -q \
    -of 'GTiff' \
    -a_srs epsg:4326 \
    -outsize $WIDTH $HEIHGT \
    -zfield value \
    -txe $LEFT $RIGHT \
    -tye $TOP $BOTTOM \
    ${DATA}/data.vrt \
    $OUTPUT

apache2ctl -D BACKGROUND

curl "http://localhost/mapserver/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&map=/data/default.map&data=/data/output.tiff&layers=default,SGG_OUTLINE&WIDTH=2048&HEIGHT=2048&CRS=EPSG%3A3857&STYLES=&BBOX=13914936.3491592,3895303.96339389,14694172.7847121,4678789.79662501" > output.png
